In [8]:
import numpy as np
a=np.array([[1,2,3],[10,34,55],[22,34,89]],int)
print(a.dtype)

int32


In [9]:
print(a.size)
print(a.shape)

9
(3, 3)


In [11]:
a.reshape(3,3)

array([[ 1,  2,  3],
       [10, 34, 55],
       [22, 34, 89]])

In [12]:
a.max(axis=0)

array([22, 34, 89])

In [13]:
a.min(axis=1)

array([ 1, 10, 22])

In [14]:
a.sum(axis=0)

array([ 33,  70, 147])

In [16]:
np.sqrt(a)
np.std(a)

27.71192193414146

In [19]:
d=np.dtype([('salary',np.float)])
arr=np.array([(1000),(20000)],dtype=d)
print(arr['salary'])

[ 1000. 20000.]


In [21]:
list=[0,2,4,6]
it=iter(list)
x=np.fromiter(it,dtype=float)
print(x)
print(type(x))

[0. 2. 4. 6.]
<class 'numpy.ndarray'>


In [23]:
arr=np.arange(0,10,2,float)
print(arr)

[0. 2. 4. 6. 8.]


In [29]:
a=np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])
for x in np.nditer(a):
    print(x,end=' ')

1 2 3 4 2 4 5 6 10 20 39 3 

In [36]:
print(np.where(a>12))
at=a.T
print(at)

(array([2, 2], dtype=int64), array([1, 2], dtype=int64))
[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]


In [33]:
print(np.char.add(['welcome','Hi'],[' to javapoint',' read python']))

['welcome to javapoint' 'Hi read python']


In [34]:
print(np.char.join(':','HM'))

H:M
